import Head from 'next/head'
import { request } from "../lib/datocms";

const HOMEPAGE_QUERY = `
  query HomePage {
    homePage {
      pageTitle
    }
  }
`;

export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY
  });
  return {
    props: { ...data }
  };
}

export default function Home({ homePage }) {
  return (
    <div>
      <Head>
        <title>Data Fetch Demo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>{homePage.pageTitle}</h1>
    </div>
  )
}
